### ISSUE TITLE
Alvaro

### ISSUE THREAD

**Issue by Konahrik1** [VaroArt/Unity-RespositoryTest#37]
- [x] Implementacion in game

- [x] Modelado 3D de referencias para matias Mendoza

- [x] Implementacion extras (decoraciones de fondo para paneles)
- [x] Modelado 3D de referencias para matias Mendoza(Centro de comunicaciones) 

- [x] Animación de extras (decoraciones para el fondo de los paneles del hud)

- [x] Animacion "No Disponible" o "error" para mecanismo de Dron

- [x] Nuevo diseño para el menu de inicio

- [x] Hacer funcional el boton de drone (que al presionarlo aparesca "no disponible")

- [x]  Hacer funcionales los botones del menu de pausa y del menu inicial

- Fecha limite 14/11 a las 19:30 hrs.

**Comment by VaroArt** [comment]
**resultado del modelado**

![satelite concept](https://user-images.githubusercontent.com/69603031/97824023-89a81480-1c99-11eb-87f4-030e7e9aa92c.png)
